# 应用服务 WEB 访问端口
server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://rm-bp1035514z9uq43q46o.mysql.rds.aliyuncs.com:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: admin_1066365803
    password: 142536aA
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #    host: 10.20.34.70
    host: 10.16.76.135
    port: 6379
    password: 142536aA




